export const ClientFieldsMap = new Map([
    ['surname', 'Фамилия'],
    ['name', 'Имя'],
    ['patronymic', 'Отчество'],
    ['birthdate', 'Дата рождения'],
    ['gender', 'Пол'],
    ['city_of_actual_residence', 'Город фактического проживания'],
    ['address_of_the_actual_residence', 'Адрес фактического проживания'],
    ['home_phone', 'Дом. номер телефона'],
    ['mob_phone', 'Моб. номер телефона'],
    ['email', 'Почта'],
    ['workplace', 'Место работы'],
    ['post', 'Должность'],
    ['city_of_residence', 'Город по прописке'],
    ['address_of_residence', 'Адрес прописки'],
    ['marital_status', 'Семейное положение'],
    ['citizenship', 'Гражданство'],
    ['retiree', 'Пенсионер'],
    ['monthly_cash_income', 'Ежемесячный доход'],
    ['liable', 'Военнообязанный'],
])

